name: Build and Upload Dist
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Decode env from secret
        run: echo "${{ secrets.FIREBASE_ENV_BASE64 }}" | base64 -d > .env
        
      - run: npm ci
      
      - run: npm run build
      
      - name: Upload dist as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 7
